name: Test
on: [pull_request, push]

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify Gamedata
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install LuaJIT
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"
      - name: Verify Gamedata
        shell: pwsh
        run: ./test/test.ps1