name: Test
on: 
  pull_request:
  push:
  schedule:
    - cron: '0 17 * * *'
  repository_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify Gamedata
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Lua 5.1
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"
      - name: Verify Gamedata
        shell: pwsh
        run: cd test && ./test.ps1
      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            test/bin
            !test/bin/.gitkeep
  plugins:
    runs-on: ubuntu-latest
    name: Build Plugins
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Plugins
        shell: pwsh
        run: cd src && ./build.ps1
      - name: Upload Plugins
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: plugins
          path: |
            src/plugins
            !src/plugins/.gitkeep